### ISSUE TITLE
Crirompov - Checklist Entregable01

### ISSUE THREAD

**Issue by crirompov** [gti-sos/SOS1718-04#16]
Cosas que me quedan por hacer:

- [x] Búsquedas por todos los campos de la app. Punto 3 de D01

- [x] Implementar paginación. Punto 4 de D01

- [x] Acceder a una estadística concreta: (1)
```
###########(1)
Petición:
	GET	.../population-stats/seville/2016
Respuesta:
{ “town”: “seville”, “year”: 2016, “population” : 500000 }

```

- [x] Actualizar una estadística:
```
Petición:
	PUT	.../population-stats/seville/2016
{ “town”: “seville”, “year”: 2016, “population” : 400000 }

```

- [x] Acceder a una estadística concreta:
```
Petición:
	GET	.../population-stats/seville/2016
Respuesta:
{ “town”: “seville”, “year”: 2016, “population” : 500000 }
```
**Está planteado pero no funciona no se porqué**
- [x] Realizar búsqueda de estadísticas de sevilla en un periodo:
```
Petición:
	GET	.../population-stats/seville?from=2014&to=2016
Respuesta:
[{ “town”: “seville”, “year”: 2016, “population” : 400000 }
 ...]

```
**Está planteado pero no funciona no se porqué**
- [x] Realizar búsqueda de estadísticas de todos las ciudades en un periodo:
```
Petición:
	GET	.../population-stats?from=2014&to=2016
Respuesta:
[{ “town”: “seville”, “year”: 2016, “population” : 400000 },
 { “town”: “seville”, “year”: 2015, “population” : 350000 },
 { “town”: “cadiz”, “year”: 2015, “population” : 75000 },
 { “town”: “cadiz”, “year”: 2014, “population” : 72000 },
 ...]

```

- [x] Acceder a todas las estadísticas de un año:
```
Petición:
	GET	.../population-stats?year=2016
Respuesta:
[ { “town”: “seville”, “year”: 2016, “population” : 500000 },
  { “town”: “cadiz”, “year”: 2016, “population” : 85000 },
  ... ]

```

**Comment by crirompov** [comment]
Las búsquedas por periodos están planteadas pero no entiendo porque no funcionan.

**Comment by carmontap** [comment]
El código que tienes que modificar en las búsquedas es este : db.find({"campo": {"$gte":cotaInferior, "$lte":cotaSuperior}}) en las tuyas tienes el endYear en la cota inferior, y el startYear en la superior por eso no te funciona.
